generator: admingenerator.generator.doctrine
params:
    model: Parabol\LocaleBundle\Entity\Country
    namespace_prefix: App
    concurrency_lock: ~
    bundle_name: LocaleAdminBundle
    pk_requirement: ~
    fields: 
        code: 
            label: Name
            formType: Symfony\Component\Form\Extension\Core\Type\CountryType
        name: 
            label: Display Name
        dialingCode:
            label: Dialing Code
        nativeCode:
            label: Native Locale Code
        locales:
            formType: Symfony\Bridge\Doctrine\Form\Type\EntityType
            addFormOptions:
                multiple: true
                expanded: true
                by_reference: false
                # choice_label: displayRequiredLabel
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: List for LocaleAdminBundle
            display: ~
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    excel:
        params: ~
        filename: ~
        filetype: ~
    new:
        params:
            title: New object for LocaleAdminBundle
            display: [code, name, currency, dialingCode, nativeCode, locales]
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "You're editing the object \"%object%\"|{ %object%: Country.name }|"
            display: [code, name, currency, dialingCode, nativeCode, locales]
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "You're viewing the object \"%object%\"|{ %object%: Country.name }|"
            display: ~
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
