generator: admingenerator.generator.doctrine
params:
    model: Parabol\LocaleBundle\Entity\Locale
    namespace_prefix: App
    concurrency_lock: ~
    bundle_name: LocaleAdminBundle
    pk_requirement: ~
    fields: 
        countries:
            formType: Symfony\Bridge\Doctrine\Form\Type\EntityType
            addFormOptions:
                multiple: true
                expanded: true
            # addFormOptions:
            #     delete_empty: true
            #     allow_delete: true
            #     entry_type: Parabol\LocaleAdminBundle\Form\Type\Country\NewType
            #     entry_options: 
            #         data_class: Parabol\LocaleBundle\Entity\Country

    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: List for Locales
            display: ~
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
                translations: 
                    label: Transaltions
                    icon: fa fa-list
    excel:
        params: ~
        filename: ~
        filetype: ~
    new:
        params:
            title: New Locale
            display: ~
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "You're editing the object \"%object%\"|{ %object%: Locale.code }|"
            display: [isEnabled, code, isDefault, isRequired, countries ]
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "You're viewing the object \"%object%\"|{ %object%: Locale.code }|"
            display: ~
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
